/** Small, gesture-unlocked Web Audio bank. Quarter-point plucks follow the
 * original Sound.tsx idea; recorded mode reuses the user's existing samples. */
export function createSound(){
 let ctx:AudioContext|undefined,master:GainNode|undefined,buffer:AudioBuffer|undefined,loading=false,mode='chords',volume=.3,lastBucket=0,lastAt=0;
 function unlock(){if(!ctx){ctx=new AudioContext();master=ctx.createGain();master.gain.value=volume;master.connect(ctx.destination);}void ctx.resume();if(!loading){loading=true;fetch(new URL('../../assets/audio/tiup-comm-out.wav',import.meta.url)).then(r=>r.arrayBuffer()).then(b=>ctx!.decodeAudioData(b)).then(b=>buffer=b).catch(()=>{});}}
 function tones(notes:number[],strength=.2,duration=.25){if(!ctx||!master||mode==='off'||ctx.state!=='running')return;const t=ctx.currentTime;notes.forEach((hz,i)=>{const o=ctx!.createOscillator(),g=ctx!.createGain();o.type='triangle';o.frequency.value=hz;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(strength/notes.length,t+.008+i*.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(master!);o.start(t+i*.012);o.stop(t+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};});}
 function sample(){if(!buffer||!ctx||!master||mode==='off')return false;const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffer;s.playbackRate.value=1.1;g.gain.value=.45;s.connect(g);g.connect(master);s.start();s.onended=()=>{s.disconnect();g.disconnect();};return true;}
 return {unlock,setMode(v:string){mode=v;},setVolume(v:number){volume=v;if(ctx&&master)master.gain.setTargetAtTime(v,ctx.currentTime,.03);},start(){lastBucket=0;tones([196],.08,.12);},progress(p:number,multiply:boolean){const bucket=Math.min(3,Math.floor(p*4));if(bucket===lastBucket)return;const reverse=bucket<lastBucket;lastBucket=bucket;if(performance.now()-lastAt<110)return;lastAt=performance.now();const root=multiply?196:261.63;tones([root*(reverse?.5:1),root*(bucket===2?1.5:2)],.09+bucket*.02,.2);},catch(){if(mode!=='recorded'||!sample())tones([523.25,783.99,1046.5],.3,.4);},uncatch(){tones([261.63,196],.12,.16);},finish(commit:boolean){tones(commit?[130.81,261.63]:[146.83],commit?.1:.05,.2);}};
}
