const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
(async()=>{const sceneId='delete-check-'+Date.now(),folder=path.resolve('scenes',sceneId),browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
 await p.goto('http://127.0.0.1:3101/explorations/018-painted-ground/?mode=body&rockLayout=enclosed&editor=1&scene='+sceneId);await p.waitForFunction(()=>document.querySelector('#sceneStatus')?.textContent.includes('Built-in scene'));await p.locator('#editScene').click();
 const state=()=>p.evaluate(async()=>{const {rockAuthoring}=await import('/explorations/018-painted-ground/rock-authoring.ts');return {saved:rockAuthoring.capture(),visible:rockAuthoring.list().map(o=>o.userData.formation.id)};});
 const save=async title=>{await p.locator('#sceneTitle').fill(title);await p.locator('#saveScene').click();await p.waitForFunction(()=>document.querySelector('#sceneStatus').textContent.startsWith('Saved “'));return p.locator('#sceneVersions').inputValue();};
 const originalVersion=await save('Before deletion');await p.locator('#editorSelection').selectOption('rock-16');await p.locator('#copyScenery').click();
 const initialPatches=await p.locator('#rockLoad').getAttribute('data-patches');
 await p.locator('#deleteScenery').click();assert.equal(await p.locator('#editorSelection').inputValue(),'');assert.equal(await p.locator('#deleteScenery').isDisabled(),true);assert.equal((await state()).visible.includes('rock-16'),false);assert.equal((await state()).saved.find(r=>r.id==='rock-16').deleted,true);assert.ok(+(await p.locator('#rockLoad').getAttribute('data-patches'))<+initialPatches);
 await p.locator('#undoScene').click();assert.equal(await p.locator('#editorSelection').inputValue(),'rock-16');assert.equal(await p.locator('#rockLoad').getAttribute('data-patches'),initialPatches);
 await p.locator('#redoScene').click();assert.equal((await state()).visible.includes('rock-16'),false);
 // A copied asset remains pasteable after the original was deleted.
 await p.locator('#pasteScenery').click();const copyId=await p.locator('#editorSelection').inputValue();assert.match(copyId,/^copy-/);await p.locator('#world canvas').focus();await p.keyboard.press('Backspace');assert.equal((await state()).saved.some(r=>r.id===copyId),false);
 await p.locator('#undoScene').click();assert.equal(await p.locator('#editorSelection').inputValue(),copyId);await p.locator('#redoScene').click();assert.equal((await state()).visible.includes(copyId),false);
 for(const id of ['rock-15','stone-0','fungus-0']){await p.locator('#editorSelection').selectOption(id);await p.locator('#world canvas').focus();await p.keyboard.press('Delete');assert.equal((await state()).visible.includes(id),false);}
 // Deleting text must not delete the selected object, and Play mode must ignore Delete.
 await p.locator('#editorSelection').selectOption('fungus-1');await p.locator('#sceneTitle').fill('Text');await p.keyboard.press('Backspace');assert.equal(await p.locator('#sceneTitle').inputValue(),'Tex');assert.equal((await state()).visible.includes('fungus-1'),true);
 await p.locator('#editScene').click();await p.locator('#world canvas').focus();await p.keyboard.press('Backspace');assert.equal((await state()).visible.includes('fungus-1'),true);await p.locator('#editScene').click();
 await p.getByRole('button',{name:'Appearance',exact:true}).click();await p.locator('#settings summary').filter({hasText:'Surroundings'}).click();await p.locator('#rockShading').selectOption('soft');await p.locator('#rockLayout').selectOption('full');assert.equal((await state()).visible.includes('fungus-0'),false);await p.locator('#rockLayout').selectOption('enclosed');assert.equal((await state()).visible.includes('rock-16'),false);await p.getByRole('button',{name:'Scene',exact:true}).click();
 await save('Deleted scenery');await p.locator('#defaultScene').click();await p.waitForFunction(()=>document.querySelector('#sceneStatus').textContent.includes('is now the default'));const snapshot=await state();
 await p.reload();await p.waitForFunction(()=>document.querySelector('#sceneStatus').textContent.includes('Loaded Deleted scenery'));assert.deepEqual(await state(),snapshot);await p.locator('#editScene').click();await p.screenshot({path:'.cache/editor/deleted-scenery.png'});
 // Earlier versions restore deleted originals without a migration.
 await p.locator('#sceneVersions').selectOption(originalVersion);await p.locator('#loadScene').click();await p.waitForFunction(()=>document.querySelector('#sceneStatus').textContent.includes('Loaded Before deletion'));assert.equal((await state()).visible.length,67);assert.equal((await state()).saved.some(r=>r.deleted),false);
 assert.deepEqual(errors,[]);console.log('Delete: original formations/props and copies, growth cleanup, undo/redo selection, clipboard after deletion, text/play isolation, shading/layout changes, durable reload and earlier-version restoration passed.');
}finally{await browser.close();await fs.rm(folder,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1)});
