const {chromium}=require('playwright');const fs=require('node:fs');const out=process.env.CANOPY_CAPTURE_DIR||'.cache/canopy-check';fs.mkdirSync(out,{recursive:true});const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1500,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto((process.env.CANOPY_URL||'http://127.0.0.1:3100/explorations/019-inhabited-trees/canopy.html'));await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.waitForTimeout(1300);
 const growth=await p.locator('body').getAttribute('data-study')==='growth';
 for(const style of (growth?['G1','G2','G3','F5']:['F5','F1','F2','F3','F6'])){await p.selectOption('#style',style);await p.waitForTimeout(700);await p.screenshot({path:out+'/'+style+'.png'});console.log(style,await p.locator('body').getAttribute('data-stats'));}
 await p.selectOption('#style','F5');
 const before=await p.evaluate(()=>window.__canopyStudy.inspect());await p.uncheck('#normals');const after=await p.evaluate(()=>window.__canopyStudy.inspect());assert.deepEqual(before.attachments,after.attachments);await p.check('#normals');
 await p.locator('#density').evaluate(e=>{e.value='1.8';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.ok((await p.evaluate(()=>window.__canopyStudy.inspect())).canopyTriangles>before.canopyTriangles);await p.locator('#density').evaluate(e=>{e.value='1';e.dispatchEvent(new Event('input',{bubbles:true}));});
 for(const construction of (growth?['G1','G2','G3']:['F5'])){await p.selectOption('#style',construction);
 for(const specimen of ['swap','group','zero']){await p.selectOption('#specimen',specimen);for(const t of [0,.25,.5,.75,1]){await p.locator('#pose').evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},t);await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.waitForTimeout(180);
 const state=await p.evaluate(()=>window.__canopyStudy.inspect());assert.ok(state.finite);for(const shoot of state.offshoots){assert.ok(shoot.position.every(Number.isFinite));assert.ok(Number.isFinite(shoot.scale)&&shoot.scale>=0&&shoot.scale<=1);}
 for(const a of state.attachments){if(a.visible){assert.ok(a.endpoint);assert.ok(a.position.every((v,i)=>Math.abs(v-a.endpoint[i])<1e-8));assert.ok(a.scale>=0&&Number.isFinite(a.scale));}}
 if(specimen==='zero'&&t===1)assert.equal(state.attachments.filter(a=>a.visible).length,6);
 if(t===.5)await p.screenshot({path:out+'/'+construction+'-'+specimen+'-mid.png'});}}
 }
 if(growth){await p.selectOption('#style','G1');await p.locator('#offshoots').evaluate(e=>{e.value='0';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal((await p.evaluate(()=>window.__canopyStudy.inspect())).offshoots.length,0);await p.locator('#offshoots').evaluate(e=>{e.value='.7';e.dispatchEvent(new Event('input',{bubbles:true}));});assert.ok((await p.evaluate(()=>window.__canopyStudy.inspect())).offshoots.length>0);}
 await p.selectOption('#specimen','mature');await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.getByText('Light spill experiment',{exact:true}).click();await p.selectOption('#spill','violet');await p.waitForTimeout(500);await p.screenshot({path:out+'/spill.png'});
 await p.selectOption('#spill','off');await p.locator('#resetView').click();await p.mouse.move(600,500);await p.mouse.down();await p.mouse.move(1050,490,{steps:40});await p.mouse.up();await p.waitForTimeout(500);await p.screenshot({path:out+'/reverse.png'});
 await p.setViewportSize({width:430,height:850});await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'/mobile.png'});assert.deepEqual(errors,[]);console.log('All styles and rewrite frames, offshoot controls, light spill and reverse view: no browser errors.');
}finally{await b.close();}})();
