const references={0:new URL('./references/state-0.png',import.meta.url).href,4:new URL('./references/state-4.png',import.meta.url).href,6:new URL('./references/state-6.png',import.meta.url).href};

const stages=[
{file:'01-arrival',art:new URL('./concepts/01-arrival.png',import.meta.url).href,prompt:new URL('./concepts/01-arrival-prompt.txt',import.meta.url).href,title:'Arrival',state:0,count:13,caption:'Fine woody offshoots carry sparse wreaths of blue-violet leaf membranes. The spirit feels awake and unsettled; the main algebra remains exposed and readable.'},
{file:'02-concentration',art:new URL('./concepts/02-concentration.png',import.meta.url).href,prompt:new URL('./concepts/02-concentration-prompt.txt',import.meta.url).href,title:'Concentration',state:4,count:9,caption:'After both zeros have been removed, the host is smaller and the energy more concentrated. Denser spectral leaves and spreading ground pulses suggest mounting pressure. This is the corrected nine-node concept.'},
{file:'03-release',art:new URL('./concepts/03-release.png',import.meta.url).href,prompt:new URL('./concepts/03-release-prompt.txt',import.meta.url).href,title:'Release',state:6,count:5,caption:'At the structural goal, a wave front carries the spectral leaves outward and the sigils begin to depart. The compact woody host remains. The eventual effect should distort a narrow band rather than fog the entire clearing.'},
{file:'04-first-leaves',art:new URL('./concepts/04-first-leaves.png',import.meta.url).href,prompt:new URL('./concepts/04-first-leaves-prompt.txt',import.meta.url).href,title:'First leaves',state:6,count:5,caption:'The spirit has gone. The tree stays small and almost bare for a moment; the first living leaves begin to unfold. This quiet interval separates the release from the return to growth.'},
{file:'05-recovered',art:new URL('./concepts/05-recovered.png',import.meta.url).href,prompt:new URL('./concepts/05-recovered-prompt.txt',import.meta.url).href,title:'Recovery',state:6,count:5,caption:'The biological tree regains roughly its former height, a finer branching crown and living green leaves. Its physical richness returns without undoing the solved expression.'}
];let selected=0,reference=false;const $=id=>document.getElementById(id),buttons=[];
function show(){const s=stages[selected];$('art').src=reference?references[s.state]:s.art;$('art').alt=reference?'Actual 018 source: '+s.count+' algebra nodes':s.title+' concept paint-over';$('full').href=$('art').getAttribute('src');$('stageTitle').textContent=String(selected+1).padStart(2,'0')+' · '+s.title;$('caption').textContent=reference?'Actual playable reference frame. '+s.count+' algebra nodes; future spirit and foliage effects are not present.':s.caption;$('basis').textContent=(reference?'Source frame':'Concept')+' · based on 018 / '+s.count+' algebra nodes';$('reference').textContent=reference?'Show concept art':'Show source screenshot';$('reference').setAttribute('aria-pressed',String(reference));$('prompt').href=s.prompt;$('prompt').download=s.file+'-prompt.txt';buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));}
stages.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<small>'+String(i+1).padStart(2,'0')+'</small>'+s.title;b.onclick=()=>{selected=i;show();};buttons.push(b);document.querySelector('.stage-buttons').append(b);});$('reference').onclick=()=>{reference=!reference;show();};show();

document.getElementById('brief').href=new URL('./README.md',import.meta.url).href;document.getElementById('provenance').href=new URL('./provenance.json',import.meta.url).href;document.getElementById('states').href=new URL('./references/states.json',import.meta.url).href;

$('foliage-full').href=new URL('./round-02/foliage.png',import.meta.url).href;
$('spirit-full').href=new URL('./round-02/spirit.png',import.meta.url).href;
$('foliage-prompt').href=new URL('./round-02/foliage-prompt.txt',import.meta.url).href;
$('spirit-prompt').href=new URL('./round-02/spirit-prompt.txt',import.meta.url).href;
$('round-two-provenance').href=new URL('./round-02/provenance.json',import.meta.url).href;
