const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const out=process.env.SHADOW_CAPTURE_DIR||'.cache/shadow-check';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto(process.env.SHADOW_URL||'http://127.0.0.1:3100/explorations/019-inhabited-trees/shadow.html');await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.waitForTimeout(800);
const slider=async(id,value)=>{await p.locator('#'+id).evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},value);await p.waitForTimeout(80);};
for(const style of ['S1','S2','S3']){await p.selectOption('#style',style);await p.waitForTimeout(500);await p.screenshot({path:out+'/'+style+'.png'});const x=await p.evaluate(()=>window.__canopyStudy.inspect());assert.ok(x.shadow.volumes>0&&x.shadow.volumes<=40);assert.ok(x.shadow.centres.flat().every(Number.isFinite));console.log(style,await p.locator('body').getAttribute('data-stats'));}
await p.selectOption('#style','S1');await p.uncheck('#arcs');await slider('fringe',0);await slider('wind',0);
// Compare actual rendered pixels: increased absorption must darken many pixels,
// while a substantial number of scene pixels retain exact brightness outside it.
const pixels=async()=>p.evaluate(async()=>{const source=document.querySelector('#view canvas'),img=new Image();img.src=source.toDataURL();await img.decode();const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const x=c.getContext('2d');x.drawImage(img,0,0);const data=x.getImageData(0,0,c.width,c.height).data;const sample=[];for(let i=0;i<data.length;i+=64)sample.push(data[i],data[i+1],data[i+2]);return sample;});
await slider('opacity',0);const clear=await pixels();await slider('opacity',.85);const dark=await pixels();let darker=0,unchanged=0,transmitting=0;for(let i=0;i<clear.length;i++){if(clear[i]-dark[i]>12){darker++;if(dark[i]>8)transmitting++;}if(Math.abs(clear[i]-dark[i])<2)unchanged++;}assert.ok(darker>1000);assert.ok(unchanged>clear.length*.5);assert.ok(transmitting>darker*.5);await p.screenshot({path:out+'/dark-transmission.png'});
await slider('opacity',.72);await slider('fringe',.55);await p.check('#arcs');await slider('anger',1);await p.waitForTimeout(250);let x=await p.evaluate(()=>window.__canopyStudy.inspect());assert.equal(x.shadow.arcs,36);await p.screenshot({path:out+'/agitated.png'});
for(const specimen of ['swap','group','zero']){await p.selectOption('#specimen',specimen);for(const t of [0,.25,.5,.75,1]){await slider('pose',t);await p.waitForFunction(()=>document.body.dataset.ready==='true');await p.waitForTimeout(90);x=await p.evaluate(()=>window.__canopyStudy.inspect());assert.ok(x.finite);assert.ok(x.shadow.centres.flat().every(Number.isFinite));assert.ok(x.shadow.radii.flat().every(v=>Number.isFinite(v)&&v>0));if(t===.5)await p.screenshot({path:out+'/'+specimen+'-mid.png'});}}
await p.getByText('Palette & local light',{exact:true}).click();await p.selectOption('#spill','blue');await p.waitForTimeout(400);await p.screenshot({path:out+'/blue.png'});await p.selectOption('#spill','amber');await p.waitForTimeout(200);await p.screenshot({path:out+'/amber.png'});await p.selectOption('#spill','violet');await p.selectOption('#specimen','mature');await p.waitForFunction(()=>document.body.dataset.ready==='true');await slider('anger',.3);await p.screenshot({path:out+'/mature.png'});
await p.mouse.move(600,500);await p.mouse.down();await p.mouse.move(1050,490,{steps:40});await p.mouse.up();await p.waitForTimeout(500);await p.screenshot({path:out+'/reverse.png'});await p.uncheck('#foliage');await p.waitForTimeout(100);assert.equal((await p.evaluate(()=>window.__canopyStudy.inspect())).shadow.volumes,0);await p.check('#foliage');await p.setViewportSize({width:430,height:850});await p.waitForTimeout(200);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log({darker,unchanged,transmitting});console.log('Shadow forms, actual transmission pixels, 15 rewrite states, palettes, orbit and visibility: passed.');}finally{await b.close();}})();
