const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const out=process.env.STORM_CAPTURE_DIR||'.cache/storm-check';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:3100/explorations/019-inhabited-trees/shadow.html');await p.waitForFunction(()=>document.body.dataset.ready==='true');
const input=async(id,value)=>{await p.locator('#'+id).evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},value);await p.waitForTimeout(70);};
await input('effectTime',2);
for(const style of ['S4','S5','S6']){await p.selectOption('#style',style);await p.waitForTimeout(250);await p.screenshot({path:out+'/'+style+'.png'});const s=await p.evaluate(()=>window.__canopyStudy.inspect().shadow);assert.ok(s.volumes>0&&s.volumes<=64);assert.ok(s.centres.flat().every(Number.isFinite));assert.ok(s.radii.flat().every(x=>Number.isFinite(x)&&x>0));}
await p.selectOption('#style','S4');
const pixels=()=>p.evaluate(async()=>{const canvas=document.querySelector('#view canvas'),img=new Image();img.src=canvas.toDataURL();await img.decode();const c=document.createElement('canvas');c.width=canvas.width;c.height=canvas.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height).data;const sample=[];for(let i=0;i<d.length;i+=64)sample.push(d[i],d[i+1],d[i+2],d[i+3]);return sample;});
await p.uncheck('#arcs');await input('fringe',0);await input('branchGlow',0);await p.selectOption('#visibility','depth');await input('opacity',.85);const depth=await pixels();await p.selectOption('#visibility','clear');await p.waitForTimeout(80);const clear=await pixels();let lifted=0,unchanged=0;for(let i=0;i<depth.length;i+=4){const difference=(clear[i]+clear[i+1]+clear[i+2])-(depth[i]+depth[i+1]+depth[i+2]);if(difference>24)lifted++;if(Math.abs(difference)<4)unchanged++;}assert.ok(lifted>30,'host visibility must have a real pixel effect');assert.ok(unchanged>depth.length/4*.8,'readability must not brighten the whole cloud');
for(const mode of ['depth','readable','clear']){await p.selectOption('#visibility',mode);await input('opacity',.72);await input('branchGlow',.4);await input('fringe',.55);await p.screenshot({path:out+'/visibility-'+mode+'.png'});}await p.selectOption('#visibility','readable');
let first;
for(const t of [0,2,4]){await input('effectTime',t);const s=await p.evaluate(()=>window.__canopyStudy.inspect().shadow);if(t===0)first=s;else assert.notDeepEqual(s.centres,first.centres,'cloud boundaries must evolve');await p.screenshot({path:out+'/roil-'+t+'.png'});}
await input('wind',0);await input('effectTime',0);const still=await p.evaluate(()=>window.__canopyStudy.inspect().shadow);await input('effectTime',4);assert.deepEqual((await p.evaluate(()=>window.__canopyStudy.inspect().shadow)).centres,still.centres,'cloud speed zero must stop geometric roiling');await input('wind',.65);
await p.getByText('Effect timing',{exact:true}).click();await p.check('#arcs');for(const anger of [.2,1]){await input('anger',anger);await p.locator('#sampleFlash').click();await p.waitForTimeout(80);const s=await p.evaluate(()=>window.__canopyStudy.inspect().shadow);assert.ok(s.arcs>8&&s.arcs<=48);assert.ok(s.arcPower>0);await p.screenshot({path:out+'/flash-'+anger+'.png'});await input('effectTime',.6);assert.equal((await p.evaluate(()=>window.__canopyStudy.inspect().shadow)).arcs,0,'flashes must fully end');}
for(const style of ['S4','S5','S6']){await p.selectOption('#style',style);for(const specimen of ['swap','group','zero']){await p.selectOption('#specimen',specimen);for(const t of [0,.25,.5,.75,1]){await input('pose',t);await p.waitForFunction(()=>document.body.dataset.ready==='true');const s=await p.evaluate(()=>window.__canopyStudy.inspect());assert.ok(s.finite);assert.ok(s.shadow.radii.flat().every(x=>Number.isFinite(x)&&x>0));if(t===.5)await p.screenshot({path:out+'/'+style+'-'+specimen+'-mid.png'});}}}
for(const style of ['S1','S2','S3']){await p.selectOption('#style',style);await p.waitForTimeout(100);const s=await p.evaluate(()=>window.__canopyStudy.inspect().shadow);assert.ok(s.volumes<=40);assert.equal(await p.locator('#visibility').isDisabled(),true);}
await p.selectOption('#style','S4');await p.selectOption('#specimen','mature');await p.waitForFunction(()=>document.body.dataset.ready==='true');await input('anger',.2);await p.screenshot({path:out+'/mature.png'});await p.mouse.move(500,500);await p.mouse.down();await p.mouse.move(1000,500,{steps:30});await p.mouse.up();await p.waitForTimeout(300);await p.screenshot({path:out+'/reverse.png'});await p.uncheck('#foliage');await p.waitForTimeout(100);assert.equal((await p.evaluate(()=>window.__canopyStudy.inspect().shadow)).volumes,0);await p.check('#foliage');await p.setViewportSize({width:430,height:850});await p.waitForTimeout(200);await p.screenshot({path:out+'/mobile.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log({lifted,unchanged});console.log('Three new forms, host masking pixels, evolution/freeze, brief forked flashes, 45 rewrite frames, legacy forms, orbit and mobile: passed.');}finally{await b.close();}})();
