import * as T from 'three';
import {createTraveller} from './traveller';
import {createRibbon} from './ribbon';
const $=(id:string)=>document.getElementById(id)!,value=(id:string)=>($(id) as HTMLSelectElement).value;
const scene=new T.Scene();scene.background=new T.Color('#89968b');scene.add(new T.HemisphereLight('#fff5d9','#506451',2));const sun=new T.DirectionalLight('#fff0d0',2.5);sun.position.set(-8,16,10);scene.add(sun);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));document.body.append(renderer.domElement);
const camera=new T.OrthographicCamera(-4,4,2.8,-2.8,.01,100);
const avatar=createTraveller(scene,s=>$('status').textContent=s),ribbon=createRibbon(scene);
$('figure').onchange=()=>avatar.choose(value('figure'));
function resize(){renderer.setSize(innerWidth,innerHeight);camera.left=-2.8*innerWidth/innerHeight;camera.right=-camera.left;camera.updateProjectionMatrix();}resize();addEventListener('resize',resize);
let last=performance.now();function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;const mode=value('motion'),working=mode==='pull'||mode==='pin',moving=mode==='step'||mode==='travel';avatar.root.position.z+=dt*(mode==='travel'?3.2:0);avatar.root.position.x+=dt*(mode==='step'?.65:0);
const p=avatar.root.position,offset=value('view')==='front'?new T.Vector3(0,2,7):value('view')==='side'?new T.Vector3(7,2,0):new T.Vector3(0,2,-7);camera.position.copy(p).add(offset);camera.lookAt(p.clone().add(value('view')==='side'?new T.Vector3(0,1.1,.8):new T.Vector3(value('view')==='back'?.6:-.6,1.1,0)));
const grip=working?p.clone().add(new T.Vector3(-1,2.15,.5)):undefined,brace=mode==='pin'?p.clone().add(new T.Vector3(1,2.15,.5)):undefined;
avatar.update(now,dt,moving,camera,grip,brace,0,working,working?{velocity:new T.Vector3(),effort:.6}:undefined);
const ends=avatar.linkEnds();ribbon.update(now,dt,true,working,ends.from,ends.to,camera,.15);renderer.render(scene,camera);document.body.dataset.character=avatar.current();document.body.dataset.motion=avatar.locomotion();}requestAnimationFrame(frame);
