const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text()+' '+m.location().url)});await page.goto('http://127.0.0.1:3100/explorations/018-painted-ground/?mode=body');await page.waitForFunction(()=>document.querySelector('#world').dataset.character==='blue-wrap'&&document.querySelector('#world').dataset.meshing==='ready');
await page.getByRole('button',{name:'Open Help',exact:true}).click();await page.locator('#approach').click();await page.waitForFunction(()=>document.querySelector('#world').dataset.near==='true');await page.waitForTimeout(2800);
await page.locator('#world canvas').focus();await page.keyboard.press('Space');
for(const name of ['blue-wrap','olive-cape']){
 const before=await page.locator('#world').evaluate(e=>({...e.dataset}));await page.locator('#settingsButton').click();await page.locator('#character').selectOption(name);await page.waitForFunction(n=>document.querySelector('#world').dataset.character===n,name);await page.locator('#closeSettings').click();const after=await page.locator('#world').evaluate(e=>({...e.dataset}));assert.equal(after.term,before.term);assert.equal(after.player,before.player);assert.equal(after.controlPhase,before.controlPhase);
 await page.locator('#hudToggle').click();await page.screenshot({path:__dirname+'/assets/avatars/'+name+'-idle.png'});await page.keyboard.press('Escape');
 await page.locator('#world canvas').focus();await page.keyboard.press('h');await page.keyboard.down('Space');await page.keyboard.press('1');await page.keyboard.down('ArrowDown');await page.waitForTimeout(550);await page.keyboard.up('ArrowDown');await page.waitForTimeout(200);
 let s=await page.locator('#world').evaluate(e=>({...e.dataset}));assert.equal(s.controlPhase,'pull');assert.equal(s.activeHand,'right');assert.equal(s.locomotion,'Hover');assert.equal(s.ribbon,'true');assert.equal(await page.locator('#character').isDisabled(),true);
 const [x,z]=s.player.split(',').map(Number),target=Math.atan2(-1-x,-3-z),difference=Math.atan2(Math.sin(+s.facing-target),Math.cos(+s.facing-target));assert(Math.abs(difference)<.02);
 await page.locator('#hudToggle').click();await page.screenshot({path:__dirname+'/assets/avatars/'+name+'-pull.png'});await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.keyboard.up('Space');await page.waitForFunction(()=>document.querySelector('#world').dataset.busy==='false');await page.waitForTimeout(500);
 await page.keyboard.press('f');await page.waitForTimeout(300);await page.locator('#hudToggle').click();await page.screenshot({path:__dirname+'/assets/avatars/'+name+'-pin.png'});await page.keyboard.press('Escape');await page.keyboard.press('f');
 console.log(name,'idle, hover pull, anatomical right, pin, ribbon, stable appearance switching verified');
}
await page.locator('#settingsButton').click();await page.locator('#character').selectOption('checkpoint');await page.waitForFunction(()=>document.querySelector('#world').dataset.character==='checkpoint');assert.deepEqual(errors,[]);console.log('Checkpoint and no browser/asset errors verified');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
