const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3100/explorations/018-painted-ground/?mode=body');await page.waitForFunction(()=>document.querySelector('#world').dataset.meshing==='ready');await page.getByRole('button',{name:'Open Help',exact:true}).click();await page.locator('#approach').click();await page.waitForFunction(()=>document.querySelector('#world').dataset.near==='true');await page.waitForTimeout(2600);await page.locator('#world canvas').focus();await page.keyboard.press('Space');await page.waitForTimeout(400);
const position=async()=>(await page.locator('#world').getAttribute('data-player')).split(',').map(Number),start=await position();
await page.keyboard.press('ArrowLeft');await page.waitForTimeout(200);const delayed=await position();assert(Math.hypot(delayed[0]-start[0],delayed[1]-start[1])<.025);
await page.waitForTimeout(2100);const adjusted=await position(),travel=Math.hypot(adjusted[0]-start[0],adjusted[1]-start[1]);assert(travel>.1&&travel<.85,'Selection should cause only a small capped step');
await page.keyboard.press('h');await page.keyboard.down('Space');await page.waitForFunction(()=>document.querySelector('#world').dataset.controlPhase==='pull');const atGrip=await position();assert.deepEqual((await page.locator('#world').getAttribute('data-grip-origin')).split(',').map(Number),atGrip);await page.waitForTimeout(900);const later=await position();assert.deepEqual(later,atGrip,'Automatic movement must stop during grip');assert.equal(await page.locator('#world').getAttribute('data-stance'),'off');assert.equal(await page.locator('#world').getAttribute('data-gesture-progress'),'0');assert.equal(await page.locator('#world').getAttribute('data-ribbon'),'true');
await page.locator('#hudToggle').click();await page.screenshot({path:__dirname+'/assets/elastic-ribbon.png'});await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.keyboard.up('Space');await page.waitForFunction(()=>document.querySelector('#world').dataset.busy==='false');await page.waitForTimeout(700);assert.equal(await page.locator('#world').getAttribute('data-ribbon'),'false');
await page.locator('#settingsButton').click();await page.locator('#bodyLink').selectOption('off');await page.locator('#stanceAssist').selectOption('off');await page.locator('#closeSettings').click();await page.locator('#world canvas').focus();await page.keyboard.down('Space');await page.waitForTimeout(400);assert.equal(await page.locator('#world').getAttribute('data-ribbon'),'false');await page.keyboard.press('Escape');await page.keyboard.up('Space');
assert.deepEqual(errors,[]);console.log('Actual selection step:',travel.toFixed(2),'units. Entry delay, grip origin, zero automatic pull, ribbon fade and Off comparisons passed.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
