import {writeFileSync} from 'node:fs';
import {problems} from './problems';
import {referenceFor,verifyReference,ReferenceSolution} from './problem-reference';
const data:Record<string,ReferenceSolution[]>={};
for(const p of problems){const primary=referenceFor(p);if(!primary)throw Error('No reference for '+p.id);const refs=[primary];
 // A second search without swap rules often reveals a different sufficient inventory.
 if(primary.rules.some(r=>r.startsWith('swap'))){const alternative=referenceFor(p,['swap-add','swap-mul']);if(alternative&&alternative.rules.join()!==primary.rules.join())refs.push(alternative);}
 refs.forEach(r=>verifyReference(p,r));data[p.id]=refs;console.log(p.id,refs.map(r=>`${r.steps.length} moves: ${r.rules.join(', ')}`).join(' | '));
}
writeFileSync('explorations/018-painted-ground/problem-metadata.ts',"// Generated by npm run problems:metadata. Verified rewrite witnesses, not minimum proofs.\nimport type {ReferenceSolution} from './problem-reference';\nexport const referenceSolutions:Record<string,ReferenceSolution[]>="+JSON.stringify(data,null,2)+';\n');
