const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const page=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3100/explorations/018-painted-ground/?mode=body');await page.waitForFunction(()=>document.querySelector('#world').dataset.character==='blue-wrap'&&document.querySelector('#world').dataset.meshing==='ready');
assert.equal(await page.locator('.dockToggle[aria-expanded="false"]').count(),3);await page.screenshot({path:__dirname+'/assets/grounded-docks-closed.png'});
await page.getByRole('button',{name:'Open Inspect',exact:true}).click();await page.selectOption('#palette','raincoat');await page.getByRole('button',{name:'Open Encounter',exact:true}).click();await page.getByRole('button',{name:'Open Rewrite',exact:true}).click();
const boxes=await page.locator('.dock').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom}}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],c=boxes[j];assert(!(a.x<c.right&&a.right>c.x&&a.y<c.bottom&&a.bottom>c.y),'Dock rectangles must not overlap');}
await page.getByRole('button',{name:'Stats',exact:true}).click();await page.waitForTimeout(800);assert.match(await page.locator('#fps').innerText(),/\d+ fps/);await page.screenshot({path:__dirname+'/assets/grounded-docks-open.png'});await page.getByRole('button',{name:'Collapse Inspect',exact:true}).click();await page.getByRole('button',{name:'Collapse Rewrite',exact:true}).click();
await page.locator('#approach').click();await page.waitForFunction(()=>document.querySelector('#world').dataset.locomotion==='Walk');await page.waitForFunction(()=>document.querySelector('#world').dataset.near==='true');await page.waitForTimeout(3000);await page.locator('#world canvas').focus();await page.keyboard.press('Space');await page.keyboard.press('h');await page.keyboard.down('Space');await page.waitForFunction(()=>document.querySelector('#world').dataset.controlPhase==='pull');
let s=await page.locator('#world').evaluate(e=>({...e.dataset}));const origin=s.player.split(',').map(Number);assert.notEqual(s.locomotion,'Hover');await page.keyboard.press('1');const moveStart=Date.now();await page.keyboard.down('ArrowDown');await page.waitForTimeout(700);await page.keyboard.up('ArrowDown');const moveSeconds=(Date.now()-moveStart)/1000;s=await page.locator('#world').evaluate(e=>({...e.dataset}));assert.equal(s.locomotion,'Walk');const pos=s.player.split(',').map(Number);console.log({origin,pos,moveSeconds,phase:s.controlPhase,grip:s.grip});assert(Math.hypot(pos[0]-origin[0],pos[1]-origin[1])<=.8*moveSeconds+.10,'Loaded walking stays below .8 world units per second');assert.equal(s.pullGain,'220');assert.equal(s.stance,'off');await page.keyboard.press('\\');await page.screenshot({path:__dirname+'/assets/grounded-yellow-pull.png'});await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.keyboard.up('Space');await page.waitForFunction(()=>document.querySelector('#world').dataset.busy==='false');
await page.getByRole('button',{name:'Open Inspect',exact:true}).click();await page.getByRole('button',{name:'Appearance',exact:true}).first().click();await page.selectOption('#character','olive-cape');await page.selectOption('#palette','ember');await page.waitForFunction(()=>document.querySelector('#world').dataset.character==='olive-cape');await page.keyboard.press('\\');await page.screenshot({path:__dirname+'/assets/grounded-red-olive.png'});await page.keyboard.press('Escape');
await page.setViewportSize({width:640,height:800});await page.getByRole('button',{name:'Open Rewrite',exact:true}).click();assert.equal(await page.locator('.dockToggle[aria-expanded="true"]').count(),1);await page.screenshot({path:__dirname+'/assets/grounded-narrow-ui.png'});assert.deepEqual(errors,[]);console.log('Grounded travel/pull, shorter body movement, gain, no auto pull, palettes, stats, collapsed and non-overlapping docks, narrow-screen accordion passed');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
