// Generated by npm run problems:metadata. Verified rewrite witnesses, not minimum proofs.
import type {ReferenceSolution} from './problem-reference';
export const referenceSolutions:Record<string,ReferenceSolution[]>={
  "clearing": [
    {
      "steps": [
        {
          "path": [],
          "rule": "swap-add",
          "result": "+(+(*(3,x),0),+(+(*(2,x),0),y))"
        },
        {
          "path": [],
          "rule": "assoc-add",
          "result": "+(+(+(*(3,x),0),+(*(2,x),0)),y)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "zero",
          "result": "*(3,x)"
        },
        {
          "path": [
            0,
            1
          ],
          "rule": "zero",
          "result": "*(2,x)"
        },
        {
          "path": [
            0
          ],
          "rule": "factor",
          "result": "*(+(3,2),x)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "assoc-add",
        "eval-add",
        "factor",
        "swap-add",
        "zero"
      ],
      "startNodes": 13,
      "targetNodes": 5,
      "peakNodes": 13
    }
  ],
  "identities": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "one",
          "result": "+(x,0)"
        },
        {
          "path": [
            0
          ],
          "rule": "zero",
          "result": "x"
        },
        {
          "path": [
            1
          ],
          "rule": "zero",
          "result": "*(y,1)"
        },
        {
          "path": [
            1
          ],
          "rule": "one",
          "result": "y"
        }
      ],
      "rules": [
        "one",
        "zero"
      ],
      "startNodes": 11,
      "targetNodes": 3,
      "peakNodes": 11
    }
  ],
  "arithmetic": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        },
        {
          "path": [
            1
          ],
          "rule": "eval-add",
          "result": "6"
        },
        {
          "path": [],
          "rule": "eval-mul",
          "result": "30"
        }
      ],
      "rules": [
        "eval-add",
        "eval-mul"
      ],
      "startNodes": 7,
      "targetNodes": 1,
      "peakNodes": 7
    }
  ],
  "left-factors": [
    {
      "steps": [
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(2,3),x)"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 7,
      "targetNodes": 3,
      "peakNodes": 7
    }
  ],
  "nested-factor": [
    {
      "steps": [
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(2,3),+(x,y))"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 11,
      "targetNodes": 5,
      "peakNodes": 11
    }
  ],
  "product-ladder": [
    {
      "steps": [
        {
          "path": [],
          "rule": "swap-mul",
          "result": "*(*(3,1),*(2,x))"
        },
        {
          "path": [],
          "rule": "assoc-mul",
          "result": "*(*(*(3,1),2),x)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "one",
          "result": "3"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-mul",
          "result": "6"
        }
      ],
      "rules": [
        "assoc-mul",
        "eval-mul",
        "one",
        "swap-mul"
      ],
      "startNodes": 7,
      "targetNodes": 3,
      "peakNodes": 7
    }
  ],
  "zero-storm": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "absorb",
          "result": "0"
        },
        {
          "path": [],
          "rule": "zero",
          "result": "+(*(2,x),*(3,x))"
        },
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(2,3),x)"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "absorb",
        "eval-add",
        "factor",
        "zero"
      ],
      "startNodes": 13,
      "targetNodes": 3,
      "peakNodes": 13
    }
  ],
  "signed-coefficients": [
    {
      "steps": [
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(7,-2),x)"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 7,
      "targetNodes": 3,
      "peakNodes": 7
    }
  ],
  "cancellation": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "factor",
          "result": "*(+(3,-3),x)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "eval-add",
          "result": "0"
        },
        {
          "path": [
            0
          ],
          "rule": "absorb",
          "result": "0"
        },
        {
          "path": [],
          "rule": "zero",
          "result": "y"
        }
      ],
      "rules": [
        "absorb",
        "eval-add",
        "factor",
        "zero"
      ],
      "startNodes": 9,
      "targetNodes": 1,
      "peakNodes": 9
    }
  ],
  "expand-collect": [
    {
      "steps": [
        {
          "path": [],
          "rule": "swap-add",
          "result": "+(*(3,x),*(2,+(x,3)))"
        },
        {
          "path": [
            1
          ],
          "rule": "distribute",
          "result": "+(*(2,x),*(2,3))"
        },
        {
          "path": [],
          "rule": "assoc-add",
          "result": "+(+(*(3,x),*(2,x)),*(2,3))"
        },
        {
          "path": [
            0
          ],
          "rule": "factor",
          "result": "*(+(3,2),x)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "eval-add",
          "result": "5"
        },
        {
          "path": [
            1
          ],
          "rule": "eval-mul",
          "result": "6"
        }
      ],
      "rules": [
        "assoc-add",
        "distribute",
        "eval-add",
        "eval-mul",
        "factor",
        "swap-add"
      ],
      "startNodes": 9,
      "targetNodes": 5,
      "peakNodes": 11
    }
  ],
  "two-crowns": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "factor",
          "result": "*(+(2,3),x)"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "eval-add",
          "result": "5"
        },
        {
          "path": [
            1
          ],
          "rule": "factor",
          "result": "*(+(4,2),y)"
        },
        {
          "path": [
            1,
            0
          ],
          "rule": "eval-add",
          "result": "6"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 15,
      "targetNodes": 7,
      "peakNodes": 15
    }
  ],
  "nested-units": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "zero",
          "result": "x"
        },
        {
          "path": [
            1
          ],
          "rule": "one",
          "result": "+(y,0)"
        },
        {
          "path": [
            1
          ],
          "rule": "zero",
          "result": "y"
        }
      ],
      "rules": [
        "one",
        "zero"
      ],
      "startNodes": 9,
      "targetNodes": 3,
      "peakNodes": 9
    }
  ],
  "branching-echoes": [
    {
      "steps": [
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(2,3),+(*(+(x,y),+(x,y)),x))"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 23,
      "targetNodes": 11,
      "peakNodes": 23
    }
  ],
  "hollow-crown": [
    {
      "steps": [
        {
          "path": [
            0
          ],
          "rule": "factor",
          "result": "*(+(3,-3),+(*(+(x,y),+(x,y)),x))"
        },
        {
          "path": [
            0,
            0
          ],
          "rule": "eval-add",
          "result": "0"
        },
        {
          "path": [
            0
          ],
          "rule": "absorb",
          "result": "0"
        },
        {
          "path": [],
          "rule": "zero",
          "result": "y"
        }
      ],
      "rules": [
        "absorb",
        "eval-add",
        "factor",
        "zero"
      ],
      "startNodes": 25,
      "targetNodes": 1,
      "peakNodes": 25
    }
  ],
  "full-span": [
    {
      "steps": [
        {
          "path": [],
          "rule": "factor",
          "result": "*(+(2,3),*(+(*(x,y),+(x,y)),+(x,+(y,x))))"
        },
        {
          "path": [
            0
          ],
          "rule": "eval-add",
          "result": "5"
        }
      ],
      "rules": [
        "eval-add",
        "factor"
      ],
      "startNodes": 31,
      "targetNodes": 15,
      "peakNodes": 31
    }
  ]
};
