const $=(id:string)=>document.getElementById(id)!;
type Mount='ink'|'hover'|'carve'|'vein'|'relief'|'pendant'|'hybrid';
const mounts:{id:Mount;title:string;desc:string;motion:string}[]=[
 {id:'ink',title:'A · An impression of light',desc:'Flat ivory marks remain camera-facing, with no enclosing badges. A quiet printed or projected language.',motion:'Contact: a thin colored halo. Clearest to read, but deliberately separate from the wood.'},
 {id:'hover',title:'B · Small floating objects',desc:'Raised ivory numbers and cut metal operators. Variable emblems have their own silhouette rather than the same plaque.',motion:'Contact: shallow depth and a shadow anchor. A development of the current scene treatment.'},
 {id:'carve',title:'C · Cut into the grain',desc:'Operators are grooves in widened hewn junctions. Atoms are marked on small terminal cut faces.',motion:'Contact: illuminate the recess. A moving joint must retain its carving, with no texture sliding.'},
 {id:'vein',title:'D · Light in the seam',desc:'Dark incisions contain a restrained living glow. The operator belongs to the wood, while the light can change with the spirit.',motion:'Contact: the seam brightens before a luminous impression lifts into the hand.'},
 {id:'relief',title:'E · Raised from the wood',desc:'Solid letterforms stand proud of a carved face. Broad bevels and long grain replace metal settings.',motion:'Contact: warm edge light. Needs a clear silhouette without bulky knobs at every joint.'},
 {id:'pendant',title:'F · Things hanging here',desc:'A junction keeps its carved operator. Quantities live on stone tokens; variables hang as little recognizable objects.',motion:'Contact: a small tether and restrained tilt. Decorative suspension must not look like a new semantic edge.'},
 {id:'hybrid',title:'G · Quiet wood, active spirit',desc:'Carved operators at rest; floating atoms for legibility. The operator lifts only when approached or gripped.',motion:'Contact: retain the groove while a ghost of the same glyph rises above it. Explored in the slider below.'},
];
let serial=0;
const value=(id:string)=>( $(id) as HTMLSelectElement).value;
function glyph(s:string,kind:'op'|'num'|'var',variant=''){
 if(kind==='var'){
  const style=variant||value('variableStyle'),second=s==='y';
  if(style==='rune')return `<path d="${second?'M -10 -14 L 8 -4 L -8 7 L 9 15 M -7 -3 L -7 13':'M -10 14 L -10 -10 L 7 -15 L 7 8 M -10 0 L 13 -5'}"/>`;
  if(style==='creature')return second?'<path d="M -15 10 Q -7 3 7 10 L 15 7 L 14 -2 M 9 6 L 7 -3 M 4 6 C -15 6 -15 -16 -2 -16 C 12 -16 13 2 1 2 C -7 2 -7 -8 0 -8"/>':'<path d="M 0 -11 V 15 M 0 -7 Q -24 -22 -18 0 Q -15 6 -2 5 Q -16 20 -16 9 M 0 -7 Q 24 -22 18 0 Q 15 6 2 5 Q 16 20 16 9 M -4 -18 L 0 -11 L 4 -18"/>';
  if(style==='relic')return second?'<path d="M -12 10 L 0 -16 L 13 10 Z M -12 10 L 3 17 L 13 10 M 0 -16 L 3 17"/>':'<path d="M -2 17 C -22 4 -11 -16 7 -18 C 19 -5 17 10 -2 17 Z M -2 17 Q 2 0 7 -18 M 1 1 L -9 -3 M 3 -5 L 11 -7"/>';
 }
 if(kind==='num'){
  const style=variant||value('numberStyle'),n=Number(s);
  if(style==='dots'&&n>0&&n<=9)return Array.from({length:n},(_,i)=>`<circle cx="${(i%3-1)*10}" cy="${(Math.floor(i/3)-(Math.ceil(n/3)-1)/2)*11}" r="2.7" fill="currentColor" stroke="none"/>`).join('');
  if(style==='tally'&&n>0&&n<=12)return Array.from({length:Math.ceil(n/5)},(_,group)=>{const k=Math.min(5,n-group*5),x=(group-(Math.ceil(n/5)-1)/2)*27;return Array.from({length:Math.min(k,4)},(_,i)=>`<path d="M ${x-9+i*6} -11 L ${x-10+i*6} 11"/>`).join('')+(k===5?`<path d="M ${x-14} 7 L ${x+13} -7"/>`:'');}).join('');
 }
 return `<text y="11" text-anchor="middle" fill="currentColor" stroke="none" font-family="Georgia,serif" font-size="${s.length>2?25:35}">${s}</text>`;
}
const paths=['M 159 315 Q 154 271 160 233','M 160 233 Q 112 202 72 109','M 160 233 Q 208 219 228 147','M 228 147 Q 202 105 181 49','M 228 147 Q 267 105 278 62'];
function definitions(id:string,burnt=false){return `<defs><linearGradient id="wood${id}" x1="0" y1="0" x2="1" y2=".4"><stop stop-color="${burnt?'#343533':'#6c6653'}"/><stop offset=".4" stop-color="${burnt?'#535650':'#aaa084'}"/><stop offset=".64" stop-color="${burnt?'#343b36':'#82765f'}"/><stop offset="1" stop-color="${burnt?'#242b29':'#615e4e'}"/></linearGradient><radialGradient id="wash${id}"><stop stop-color="#eef0df"/><stop offset="1" stop-color="#c7d0c2"/></radialGradient></defs>`;}
function trunk(id:string){return `<ellipse cx="168" cy="313" rx="65" ry="10" fill="#64715c" opacity=".14"/>`+paths.map((d,i)=>`<path d="${d}" fill="none" stroke="#53594c" stroke-width="${[32,22,25,16,16][i]}" stroke-linecap="butt"/><path d="${d}" fill="none" stroke="url(#wood${id})" stroke-width="${[28,18,21,12,12][i]}" stroke-linecap="butt"/><path d="${d}" fill="none" stroke="#ded5ae" stroke-width="1.5" opacity=".23" transform="translate(-3 0)"/>`).join('')+'<path d="M 148 295 L 119 318 L 153 310 M 168 298 L 196 320 L 163 310" fill="#6b6c58"/>';}
function sigil(s:string,kind:'op'|'num'|'var',mount:Mount,id:string,attention='quiet',variant='',offset=0){
 const g=glyph(s,kind,variant),wood=`url(#wood${id})`;let body='',color='#fff6d8',overlay='';
 const cut=mount==='carve'||mount==='vein'||mount==='relief'||mount==='pendant'&&kind==='op'||mount==='hybrid'&&kind==='op';
 if(cut){body=`<path d="M -23 -18 L -9 -26 L 20 -19 L 25 10 L 9 24 L -22 17 Z" fill="${wood}" stroke="#665f4e" stroke-width="2"/><path d="M -18 -14 Q 0 -23 18 -12 M -19 15 Q -1 23 17 12" fill="none" stroke="#d8cba0" stroke-width="1" opacity=".35"/>`;
  if(mount==='relief'){body+=`<g transform="translate(2 3)" color="#373c31" stroke-width="5">${g}</g><g transform="translate(-1 -1)" color="#d0bc8d" stroke-width="3">${g}</g>`;color='#a89673';}
  else {body+=`<g color="#282f2a" stroke-width="5">${g}</g><g transform="translate(.7 1)" color="#d5c19a" opacity=".4" stroke-width="1">${g}</g>`;color=mount==='vein'?'#a9d6c1':'#363a2f';}
 }else if(mount==='pendant'){body='<path d="M 0 -36 Q -12 -22 0 -17 Q 10 -22 0 -29" fill="none" stroke="#8e8365" stroke-width="2"/>';if(kind==='num')body+='<path d="M -23 -17 L 13 -23 L 25 -4 L 17 23 L -19 19 L -26 1 Z" fill="#899488" stroke="#626f65" stroke-width="2"/>';color=kind==='num'?'#f7edcf':'#657c70';}
 else if(mount==='hover'||mount==='hybrid'){body='<ellipse cx="3" cy="13" rx="19" ry="9" fill="#2c3c30" opacity=".17"/>';if(kind==='op')body+='<path d="M -19 -16 L 17 -19 L 23 7 L 9 22 L -22 14 Z" fill="#817e60" stroke="#c2b78e" stroke-width="2"/>';body+=`<g transform="translate(2.5 3)" color="#4f6459" stroke-width="4">${g}</g>`;}
 if(attention!=='quiet'){const opacity=attention==='grip'?.7:.28;overlay=`<g style="filter:blur(1.3px)" color="#bae7ce" opacity="${opacity}" stroke-width="7">${g}</g>`;}
 return `<g fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${body}<g transform="translate(${offset?offset*.5:0} ${-offset})">${overlay}<g color="${color}">${g}</g></g></g>`;
}
const nodes=[{x:160,y:233,s:'+',kind:'op'},{x:72,y:109,s:'5',kind:'num'},{x:228,y:147,s:'×',kind:'op'},{x:181,y:49,s:'x',kind:'var'},{x:278,y:62,s:'3',kind:'num'}] as const;
function tree(mount:Mount){const id=String(++serial),attention=value('attention'),burnt=value('woodStyle')==='burnt';return `<svg viewBox="0 0 340 345" role="img" aria-label="${mounts.find(m=>m.id===mount)!.title}: five plus x times three">${definitions(id,burnt)}<rect width="340" height="345" fill="url(#wash${id})"/>${trunk(id)}${nodes.map(n=>`<g transform="translate(${n.x} ${n.y+(mount==='pendant'&&n.kind!=='op'?10:0)})">${sigil(n.s,n.kind,mount,id,n.s==='×'?attention:'quiet','',mount==='hybrid'&&n.s==='×'&&attention!=='quiet'?attention==='grip'?17:6:0)}</g>`).join('')}${($('annotations') as HTMLInputElement).checked?'<g font-family="system-ui" font-size="8" letter-spacing="1.3" fill="#5f7163"><text x="17" y="75">QUANTITY</text><text x="157" y="19">IDENTITY</text><text x="245" y="188">OPERATOR</text></g>':''}</svg>`;}
function render(){ $('mountGrid').innerHTML=mounts.map(m=>`<article class="mount"><div class="art">${tree(m.id)}</div><div class="copy"><h3>${m.title}</h3><p>${m.desc}</p><p class="mechanic">${m.motion}</p></div></article>`).join('');$('key').textContent='Same expression in every card: 5 + (x × 3). '+(value('variableStyle')==='letter'?'Variable x stays a letter.':value('variableStyle')==='rune'?'The hooked mark stands for x.':value('variableStyle')==='creature'?'The moth stands for x.':'The leaf-shaped relic stands for x.')+' Attention preview targets the multiplication junction.';}
for(const id of ['variableStyle','numberStyle','woodStyle','attention','annotations'])$(id).addEventListener('change',render);
function sample(sheet:string,label:string,s:string,kind:'op'|'num'|'var',mount:Mount,variant=''){const id=String(++serial),fig=document.createElement('figure');fig.innerHTML=`<svg viewBox="0 0 110 86" role="img" aria-label="${label}">${definitions(id)}<g transform="translate(55 43)">${sigil(s,kind,mount,id,'quiet',variant)}</g></svg><figcaption>${label}</figcaption>`;$(sheet).append(fig);}
for(const [mount,label] of [['carve','Cut'],['vein','Inlaid'],['relief','Raised'],['hover','Floating']] as const)for(const op of ['+','×'])sample('operatorSheet',`${label} ${op}`,op,'op',mount);
for(const [n,style,label] of [['5','numeral','5 · numeral'],['5','dots','5 · grouped dots'],['5','tally','5 · cut tally'],['12','tally','12 · grouped tallies'],['0','numeral','0 · explicit zero'],['-12','numeral','−12 · signed quantity'],['37','numeral','37 · positional digits'],['137','numeral','137 · compact fallback']])sample('numberSheet',label,n,'num','hover',style);
for(const [style,label] of [['letter','Letter'],['rune','Invented mark'],['creature','Creature'],['relic','Relic']])for(const variable of ['x','y'])sample('variableSheet',`${label} · ${variable}`,variable,'var','ink',style);
let playing=false,start=0;
function lift(){const t=+($('lift') as HTMLInputElement).value,id=String(++serial),phase=t<.25?'Approach':t<.7?'Lift and hold':'Return',height=Math.sin(Math.PI*t)*44,x=Math.sin(Math.PI*t)*30;$('liftValue').textContent=Math.round(t*100)+'% · '+phase;
 $('liftStudy').innerHTML=`<svg viewBox="0 0 600 235" role="img" aria-label="An operator's glowing impression lifts away from its carved junction and returns">${definitions(id)}<path d="M 295 239 L 295 153 L 203 52 M 295 153 L 401 49" stroke="url(#wood${id})" stroke-width="31" fill="none"/><g transform="translate(295 153)">${sigil('+','op','carve',id)}</g><path d="M 295 153 Q 270 120 ${295-x} ${153-height}" fill="none" stroke="#adc8ae" stroke-width="2" opacity="${Math.sin(Math.PI*t)*.6}"/><g transform="translate(${295-x} ${153-height})" opacity="${Math.sin(Math.PI*t)}" color="#f4f6d4" stroke="currentColor" stroke-width="2">${glyph('+','op')}</g><g font-family="system-ui" font-size="12" fill="#526755"><text x="24" y="28">${phase}</text><text x="24" y="208">The cut stays in the wood.</text><text x="360" y="208">The impression follows the hand.</text></g></svg>`;}
$('lift').addEventListener('input',()=>{playing=false;$('playLift').textContent='Play transition';lift();});$('playLift').onclick=()=>{playing=!playing;start=performance.now();$('playLift').textContent=playing?'Pause':'Play transition';};function tick(now:number){if(playing){const t=Math.min(1,(now-start)/4500);($('lift') as HTMLInputElement).value=String(t);lift();if(t===1){playing=false;$('playLift').textContent='Play transition';}}requestAnimationFrame(tick);}render();lift();requestAnimationFrame(tick);
