import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Term,Action,initial,walk,count,format,find,actions,replace,solved,hint} from './algebra';import {Pose,layout,transition} from './layout';import {Options,prepare} from './surface';import {makeShading} from './shading';
const $=(id:string)=>document.getElementById(id)!,value=(id:string)=>($(id) as HTMLInputElement).value;
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#bac7c1');renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;$('world').append(renderer.domElement);
const scene=new T.Scene();scene.fog=new T.Fog('#bac7c1',26,60);scene.add(new T.HemisphereLight('#fff5d9','#506451',2));const sun=new T.DirectionalLight('#fff0d0',2.5);sun.position.set(-8,16,10);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:18,bottom:-18});sun.shadow.bias=-.001;scene.add(sun);
const camera=new T.OrthographicCamera(-14,14,10,-10,.1,90);camera.position.set(13,12,21);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enableDamping=true;controls.minZoom=.65;controls.maxZoom=2;controls.maxPolarAngle=Math.PI*.48;controls.mouseButtons={LEFT:null as any,MIDDLE:T.MOUSE.DOLLY,RIGHT:T.MOUSE.ROTATE};controls.update();
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.left=-11*w/h;camera.right=11*w/h;camera.top=11;camera.bottom=-11;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
const rockMat=new T.MeshStandardMaterial({color:'#6e7c76',roughness:1,flatShading:true}),mossMat=new T.MeshStandardMaterial({color:'#718565',roughness:1,flatShading:true});
function mesh(geo:T.BufferGeometry,mat:T.Material,pos:T.Vector3,scale?:T.Vector3){const m=new T.Mesh(geo,mat);m.position.copy(pos);if(scale)m.scale.copy(scale);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
mesh(new T.CylinderGeometry(16,17,1,64),new T.MeshStandardMaterial({color:'#87957c',roughness:1}),new T.Vector3(0,-.52,0));
const obstacles:{x:number;z:number;r:number}[]=[];
const rand=(n:number)=>{const v=Math.sin(n*127.1+311.7)*43758.5453;return v-Math.floor(v);};
for(let i=0;i<42;i++){const angle=i*2.3999,r=8+rand(i)*6,x=Math.cos(angle)*r,z=Math.sin(angle)*r;if(z>5&&Math.abs(x)<4)continue;const s=.6+rand(i+4)*1.8;const stone=mesh(new T.IcosahedronGeometry(1,0),rockMat,new T.Vector3(x,s*.27-.1,z),new T.Vector3(s,s*.55,s*.8));stone.rotation.set(rand(i)*.3,rand(i+3)*6,.1);obstacles.push({x,z,r:s*.8});if(i%2===0)mesh(new T.IcosahedronGeometry(1,1),mossMat,new T.Vector3(x,s*.47,z),new T.Vector3(s*.75,.13,s*.55));}
for(let i=0;i<9;i++){const z=8-i*1.1;mesh(new T.CylinderGeometry(.36,.44,.09,6),new T.MeshStandardMaterial({color:i%2?'#c3c3a9':'#adb79d',roughness:1}),new T.Vector3(Math.sin(i)*.24,.02,z),new T.Vector3(1,1,1.3));}
const treeOrigin=new T.Vector3(-1,0,-3),hero=new T.Group();hero.position.copy(treeOrigin);scene.add(hero);
const ring=mesh(new T.RingGeometry(5.5,5.58,80),new T.MeshBasicMaterial({color:'#e6ddb7',side:T.DoubleSide,transparent:true,opacity:.45}),treeOrigin.clone().setY(.025));ring.rotation.x=-Math.PI/2;
const avatar=new T.Group();avatar.position.set(0,0,9);scene.add(avatar);const cloak=new T.Mesh(new T.ConeGeometry(.3,.65,7),new T.MeshToonMaterial({color:'#475e70'}));cloak.position.y=.52;avatar.add(cloak);const head=new T.Mesh(new T.SphereGeometry(.17,12,8),new T.MeshToonMaterial({color:'#e5cfa6'}));head.position.y=.97;avatar.add(head);
const handMat=new T.MeshToonMaterial({color:'#a5c9b5'});const hands=[-1,1].map(side=>{const m=new T.Mesh(new T.IcosahedronGeometry(.12,1),handMat);m.position.set(side*.42,.65,-.05);avatar.add(m);return m;});
const halo=new T.Mesh(new T.RingGeometry(.34,.39,32),new T.MeshBasicMaterial({color:'#e8e0b2',side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.02;avatar.add(halo);
const treeShade=makeShading(),gradient=new T.DataTexture(new Uint8Array([45,110,185,255]),4,1,T.RedFormat);gradient.minFilter=gradient.magFilter=T.NearestFilter;gradient.needsUpdate=true;
const wood=()=>new T.MeshStandardMaterial({color:'#bba078',roughness:.9});const cel=()=>new T.MeshToonMaterial({color:'#bba078',gradientMap:gradient});
const materials={carved:treeShade.carved(wood()),cel:treeShade.carved(cel()),smooth:wood(),smoothCel:cel()};
const treeMesh=new T.Mesh<T.BufferGeometry,T.Material>(new T.BufferGeometry(),materials.carved);treeMesh.position.y=5;treeMesh.scale.setScalar(6);treeMesh.castShadow=true;treeMesh.receiveShadow=true;hero.add(treeMesh);
const runes=new T.Group();hero.add(runes);const textures=new Map<string,T.CanvasTexture>();
function rune(text:string,selected:boolean){const k=text+selected;let map=textures.get(k);if(!map){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=selected?'#e4c981':'#f4efd8';ctx.strokeStyle=selected?'#92753a':'#66806b';ctx.lineWidth=7;ctx.beginPath();ctx.arc(64,64,51,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#334c3d';ctx.font='bold 66px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,64,65);map=new T.CanvasTexture(c);textures.set(k,map);}return new T.SpriteMaterial({map,depthTest:false});}
let tree=initial(),selected=tree.id,steps=0,history:{tree:Term;steps:number}[]=[],future:{tree:Term;steps:number}[]=[],near=false,loaded=false,epoch=0,shapeSeed=2,spread=1,navTarget:T.Vector3|undefined,suggested:{id:string;key:string}|undefined;
let animation:{before:Term;after:Term;start:number;kind:string;merge:Record<string,string>}|undefined,poseNow:Pose|undefined,lastKey='',idCounter=0;
function options():Options{return {thickness:+value('thickness'),taper:+value('taper'),bow:+value('bow'),random:+value('random'),twist:+value('twist'),facets:+value('facets'),seed:shapeSeed,blend:+value('blend'),hewn:value('surface')==='hewn',spread};}
function layoutOptions(){return {spread,seed:shapeSeed,irregularity:+value('irregularity'),height:value('height')};}
function updateRunes(pose:Pose){runes.children.forEach(o=>(o as T.Sprite).material.dispose());runes.clear();for(const [id,n] of pose.nodes){const p=pose.points.get(id);if(!p)continue;const s=new T.Sprite(rune(n.kind==='op'?(n.op==='*'?'×':'+'):n.kind==='num'?String(n.value):n.name,id===selected));s.position.copy(p).add(new T.Vector3(0,.22,.05));s.scale.setScalar(id===selected?.95:.74);s.userData.nodeId=id;s.renderOrder=10;runes.add(s);}runes.visible=near;}
type Job={id:number;kind:'hero'|'deco';epoch:number;pose:Pose;options:Options;resolution:number;final:boolean;origin?:T.Vector3;scale?:number};
let queue:Job[]=[],inflight:Job|undefined;const worker=new Worker(new URL('./mesh.worker.ts',import.meta.url),{type:'module'});
function pump(){if(inflight||!queue.length)return;inflight=queue.shift()!;worker.postMessage({id:inflight.id,edges:inflight.pose.edges,options:inflight.options,resolution:inflight.resolution});}
function submit(job:Job){if(job.kind==='hero')queue=queue.filter(j=>j.kind!=='hero');queue.push(job);pump();}
worker.onmessage=event=>{const job=inflight;inflight=undefined;const data=event.data;if(!job||data.id!==job.id){pump();return;}if(data.error){$('message').textContent='The surface could not be rebuilt: '+data.error;animation=undefined;ui();pump();return;}
 const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(data.position,3));geo.setAttribute('normal',new T.BufferAttribute(data.normal,3));geo.computeBoundingSphere();
 if(job.kind==='hero'&&job.epoch===epoch){treeMesh.geometry.dispose();treeMesh.geometry=geo;const members=data.edges.map((e:any)=>prepare({...e,a:new T.Vector3(e.a.x,e.a.y,e.a.z),b:new T.Vector3(e.b.x,e.b.y,e.b.z)},job.options));const shifted=members.map((m:any)=>({...m,e:{...m.e,a:m.e.a.clone().add(treeOrigin),b:m.e.b.clone().add(treeOrigin)},points:m.points.map((p:T.Vector3)=>p.clone().add(treeOrigin))}));treeShade.feed(shifted,job.options);poseNow=job.pose;updateRunes(job.pose);loaded=true;$('loading').hidden=true;$('cost').textContent=`${data.position.length/9|0} triangles · ${Math.round(data.ms)} ms worker rebuild. Camera and walking stay on the main thread.`;$('world').dataset.nodes=String(count(tree));$('world').dataset.term=format(tree);$('world').dataset.meshing='ready';
  if(job.final&&animation){animation=undefined;selected=find(tree,selected)?selected:tree.id;ui();}else if(!animation)ui(false);
 }else if(job.kind==='deco'){const s=job.scale!;const mat=new T.MeshStandardMaterial({color:'#7d8b77',roughness:1});const obj=new T.Mesh(geo,mat);obj.scale.setScalar(6*s);obj.position.copy(job.origin!).add(new T.Vector3(0,5*s,0));obj.castShadow=true;scene.add(obj);}else geo.dispose();pump();};
worker.onerror=e=>{$('loading').textContent='Tree renderer error: '+e.message;};
function requestPose(now:number){const u=animation?Math.min(1,(now-animation.start)/1300):1;const quant=Math.round(u*36)/36;const config=layoutOptions();const key=JSON.stringify([epoch,tree.id,format(tree),animation?.kind,quant,Math.round(spread*25),config,options(),value('resolution')]);if(key===lastKey)return;lastKey=key;
 const pose=animation?transition(animation.before,animation.after,quant,config,animation.kind,animation.merge):layout(tree,config);submit({id:++idCounter,kind:'hero',epoch,pose,options:options(),resolution:+value('resolution'),final:!animation||quant===1});$('world').dataset.meshing='working';}
for(const [x,z,scale] of [[-8,-5,.6],[7,-7,.75]]){const root=initial();const t=root.kind==='op'?root.left:root;const opt={...options(),spread:1,thickness:.9,bow:.45,seed:Math.round(x+20)};submit({id:++idCounter,kind:'deco',epoch,pose:layout(t,{spread:1,irregularity:.5,height:'depth',seed:opt.seed}),options:opt,resolution:64,final:true,origin:new T.Vector3(x,0,z),scale});}
function status(text:string){$('message').textContent=text;}
function nextClue(){
 const nodes=walk(tree);
 if(nodes.some(n=>n.kind==='num'&&n.value===0))return 'Click a rune to select its branch. Remove the zeros and bring the two x-products together.';
 if(nodes.some(n=>actions(n).some(a=>a.key.startsWith('factor'))))return 'The x-products now share a junction. Select their + rune to factor out the common x.';
 if(nodes.some(n=>actions(n).some(a=>a.key==='calculate')))return 'The numeric leaves can combine. Select their junction to finish the simplification.';
 return 'Bring the two x-products under one + junction. Swapping and regrouping preserve the whole branches.';
}
function ui(updateMessage=true){const done=solved(tree)&&!animation;$('expression').textContent=format(tree);$('progress').textContent=`${count(tree)} nodes · ${steps} moves · start: 13 nodes`;$('bar').style.width=Math.min(100,Math.max(0,(13-count(tree))/8*100))+'%';$('goal').textContent=done?'5×x + y · same meaning, less structure.':'Simplify this tree to 5×x + y.';$('guideTitle').textContent=done?'The canopy is untangled':near?'Listen, then reshape':'Meet the tree';$('approach').hidden=near;$('hint').hidden=!near||done;($('hint') as HTMLButtonElement).disabled=!!animation||!loaded;
 ($('undo') as HTMLButtonElement).disabled=!history.length||!!animation;($('redo') as HTMLButtonElement).disabled=!future.length||!!animation;($('reset') as HTMLButtonElement).disabled=!!animation;($('settingsButton') as HTMLButtonElement).disabled=!!animation;
 for(const control of document.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('#settings input,#settings select,#seed'))control.disabled=!!animation;
 $('selection').hidden=!near||!loaded;const n=find(tree,selected);$('actions').replaceChildren();$('outline').replaceChildren();
 if(n){$('selectedLabel').textContent=format(n);$('selectedHelp').textContent=n.kind==='op'?'Choose a valid rewrite for this branch.':'This is a leaf. Select a + or × junction to reshape its expression.';
 for(const a of actions(n)){const b=document.createElement('button');b.textContent=a.label;const small=document.createElement('small');small.textContent=a.detail;b.append(small);b.disabled=!!animation||spread>.12;if(suggested?.id===n.id&&suggested.key===a.key)b.className='suggested';b.onclick=()=>apply(n,a);$('actions').append(b);}
 }
 for(const node of walk(tree)){const b=document.createElement('button');b.textContent=(node.kind==='op'?'◇ ':'· ')+format(node);b.onclick=()=>select(node.id);b.disabled=!!animation;$('outline').append(b);}
 if(updateMessage)status(done?'You used local rewrites to uncover the simpler tree. Undo to explore another route, or walk away and let it spread again.':animation?'The selected structure is changing…':near?nextClue():'Walk into its pale stone circle. The branches will settle into a working plane.');
 if(poseNow)updateRunes(poseNow);}
function select(id:string){if(animation||!near)return;selected=id;ui(false);}
function apply(n:Term,a:Action){if(animation||!near||spread>.12)return;history.push({tree,steps});future=[];const before=tree;tree=replace(tree,n.id,a.result);steps++;selected=a.result.id;suggested=undefined;epoch++;animation={before,after:tree,start:performance.now(),kind:a.key,merge:a.merge??{}};lastKey='';ui();}
$('hint').onclick=()=>{if(!near||animation)return;const h=hint(tree);if(h){selected=h.nodeId;suggested={id:h.nodeId,key:h.action.key};ui(false);status(`Try “${h.action.label}” on ${format(find(tree,h.nodeId)!)}. The suggested move is outlined in gold.`);}else status('Try bringing like products next to one another, or undo a move to explore another route.');};
$('undo').onclick=()=>{if(animation||!history.length)return;future.push({tree,steps});const prev=history.pop()!;tree=prev.tree;steps=prev.steps;epoch++;selected=tree.id;suggested=undefined;lastKey='';ui();};
$('redo').onclick=()=>{if(animation||!future.length)return;history.push({tree,steps});const next=future.pop()!;tree=next.tree;steps=next.steps;epoch++;selected=tree.id;suggested=undefined;lastKey='';ui();};
$('reset').onclick=()=>{if(animation)return;tree=initial();selected=tree.id;history=[];future=[];steps=0;epoch++;suggested=undefined;lastKey='';ui();};
$('approach').onclick=()=>navTarget=new T.Vector3(0,0,1.7);
$('settingsButton').onclick=()=>$('settings').hidden=!$('settings').hidden;$('closeSettings').onclick=()=>$('settings').hidden=true;
$('lighting').onchange=()=>{treeMesh.material=materials[value('lighting') as keyof typeof materials];};
for(const id of ['surface','resolution','thickness','taper','bow','random','irregularity','twist','facets','blend','spread','height'])$(id).addEventListener('input',()=>{lastKey='';});$('seed').onclick=()=>{shapeSeed++;lastKey='';};
const keys=new Set<string>();addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select,textarea'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());navTarget=undefined;}if(e.key==='Escape'){$('settings').hidden=true;selected=tree.id;ui(false);}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>keys.clear());
const ray=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0);let downX=0,downY=0;
renderer.domElement.addEventListener('pointerdown',e=>{downX=e.clientX;downY=e.clientY;renderer.domElement.focus();});renderer.domElement.tabIndex=0;
renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0||Math.hypot(e.clientX-downX,e.clientY-downY)>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);if(near){const hits=ray.intersectObjects(runes.children);if(hits.length){select(hits[0].object.userData.nodeId);return;}}const p=ray.ray.intersectPlane(plane,new T.Vector3());if(p&&Math.hypot(p.x,p.z)<14)navTarget=p.setY(0);});
let last=performance.now(),nearOld=false;
function tick(now:number){requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000);last=now;if(document.hidden)return;
 const move=new T.Vector3((keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),0,(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0));
 if(navTarget){move.copy(navTarget).sub(avatar.position);if(move.length()<.12){navTarget=undefined;move.setScalar(0);}}
 if(move.lengthSq()>.001){move.normalize();const proposed=avatar.position.clone().addScaledVector(move,dt*3.6);if(Math.hypot(proposed.x,proposed.z)<14.5&&!obstacles.some(o=>Math.hypot(proposed.x-o.x,proposed.z-o.z)<o.r+.3)){avatar.position.copy(proposed);avatar.rotation.y=Math.atan2(move.x,move.z);}else navTarget=undefined;cloak.rotation.z=Math.sin(now*.016)*.05;}else cloak.rotation.z=0;
 hands.forEach((m,i)=>m.position.y=.65+Math.sin(now*.002+i)*.06);
 near=Math.hypot(avatar.position.x-treeOrigin.x,avatar.position.z-treeOrigin.z)<5.5;
 const target=near?0:+value('spread');const next=spread+(target-spread)*(1-Math.exp(-dt*4));spread=Math.abs(next-target)<.008?target:Math.round(next*1000)/1000;
 if(near!==nearOld){nearOld=near;ui();}runes.visible=near;(ring.material as T.MeshBasicMaterial).color.set(solved(tree)?'#f1ce79':near?'#e6ddb7':'#bac8a8');
 if(!animation&&spread===0&&near&&document.querySelector<HTMLButtonElement>('#actions button')?.disabled)ui(false);
 requestPose(now);controls.update();renderer.render(scene,camera);$('world').dataset.near=String(near);$('world').dataset.busy=String(!!animation);$('world').dataset.player=`${avatar.position.x.toFixed(2)},${avatar.position.z.toFixed(2)}`;
}ui();requestAnimationFrame(tick);
