import {example,expr,Rule,Complexity,Path,Mapping} from './model';
import {drawing,Options,View} from './drawing';
const $=(id:string)=>document.getElementById(id)!;
const value=(id:string)=>($(id) as HTMLSelectElement).value;
let t=0,playing=false,last=0;
const opts=():Options=>({rule:value('rule') as Rule,complexity:value('complexity') as Complexity,path:value('path') as Path,view:value('view') as View,mapping:value('mapping') as Mapping,t});
function frame(){const o=opts();$('stage').innerHTML=drawing(o);($('time') as HTMLInputElement).value=String(Math.round(t*1000));$('percent').textContent=Math.round(t*100)+'%';}
function refresh(){const o=opts(),e=example(o.rule,o.complexity,o.mapping);$('equation').textContent=expr(e.before)+' → '+expr(e.after);$('event').textContent=JSON.stringify(e.edit,null,2);
 ($('mapping') as HTMLSelectElement).disabled=o.rule!=='regroup';
 ($('path') as HTMLSelectElement).disabled=o.rule!=='swap';
 $('note').textContent=o.rule==='swap'?(o.path==='flat'?'Both operands keep their internal structure, but their roots coincide halfway through this straight path. The overlap is deliberate for comparison.':'The operands follow opposite half-circles in the horizontal depth plane. Root separation stays constant; the internal subtree travels rigidly with its root.'):o.rule==='regroup'?'A, B and C stay in place. Blue p and purple q retain their identities. Compare which plus becomes the final outer operator.':'The original operand stays intact. First the plus extends from it; then zero emerges from the plus. In the plateau view, zero rises from the support surface.';
 $('policy').textContent=o.rule==='swap'?'Swap changes two ordered child slots atomically. The orbit preserves root separation, not clearance of arbitrary thick branches or attachments.':o.rule==='regroup'?(o.view==='plateaus'?(o.mapping==='exchange-roles'?'Blue p contracts from outer support to inner shelf, while purple q expands into the outer support. Both remain solid and visible; operand stacks stay fixed. Intermediate overlap is a support-morph hypothesis, not solved terrain geometry.':'Blue p remains the base. Purple q slides from beneath A/B to beneath B/C without fading. The intermediate surface passes beneath the stationary stacks; continuous support and contact still need a 3D solution.'):(o.mapping==='exchange-roles'?'p(q(A,B),C) → q(A,p(B,C)). A stays with q and C stays with p. Only B transfers along the connecting member; the two pluses trade inner/outer roles. The dashed stem shows the context attachment.':'p(q(A,B),C) → p(A,q(B,C)). p stays the root, q moves across. A slides from q to p and C slides from p to q; B stays with q. The dashed stem shows the fixed context attachment.')):(o.view==='plateaus'?'Zero is extruded upward from a fixed footprint on the base. Its sides lengthen as the top rises; it never fades. The common display support is already present before the semantic plus is introduced.':'The new plus pulls down from A to establish the context. Zero then slides outward from the plus along a growing member, at full opacity; the plus masks its initial overlap. Scrub backward to retract it.');
 $('frames').innerHTML=[0,.5,1].map((phase,i)=>`<button class="frame" data-t="${phase}"><strong>${['Before','Midpoint · geometric state','After'][i]}</strong>${drawing({...o,t:phase})}</button>`).join('');frame();}
for(const id of ['rule','complexity','path','view','mapping'])$(id).onchange=()=>{playing=false;$('play').textContent='Play';t=0;refresh();};
$('time').oninput=()=>{playing=false;$('play').textContent='Play';t=Number(value('time'))/1000;frame();};
$('frames').onclick=e=>{const b=(e.target as HTMLElement).closest<HTMLElement>('[data-t]');if(b){t=Number(b.dataset.t);playing=false;$('play').textContent='Play';frame();}};
$('play').onclick=()=>{playing=!playing;if(playing&&t>=1)t=0;$('play').textContent=playing?'Pause':'Play';};
function tick(now:number){if(playing){t=Math.min(1,t+Math.min(50,now-last)/4000);frame();if(t===1){playing=false;$('play').textContent='Replay';}}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);
$('export').onclick=()=>{const o=opts(),url=URL.createObjectURL(new Blob([drawing(o)],{type:'image/svg+xml'})),a=document.createElement('a');a.href=url;a.download=`004-${o.rule}-${o.complexity}-${o.view}-${o.path}-${o.mapping}-${Math.round(t*100)}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};refresh();
